#  imports random module for use later in the file.
import random
# print statements to introduce the name of the game and rule.
print("Welcome to Guess the Number!")
print("The rules are simple. I will think of a number, and you will try to guess it.")
# variable to store the random number generated by the randint function.
number = random.randint(1,10)
# track if user guessed num correctly
isGuessRight = False
# while loop to contain game logic.
# stopping condition to exit loop or trigger first conditional
while isGuessRight != True:
    # input function to get user guess
    guess = input("Guess a number between 1 and 10: ")
    # conditional to check if guess is correct
    if int(guess) == number:
        # print statement to congratulate user on correct guess
        print("You guessed {}. That is correct! You win!".format(guess))
        # set isGuessRight to True to exit while loop
        isGuessRight = True
    else:
        # print statement to inform user of incorrect guess and triggers loop to run again
        print("You guessed {}. Sorry that isn't it. Try again.".format(guess))